# --------------------------------------------------------------------------
# Firmware for the pi-pic-proto-hat (v2)
#
# Author: Bernhard Bablok
#
# https://github.com/bablokb/pi-pic-proto-hat
# 
# --------------------------------------------------------------------------

PROJECT=pic-firmware
EXTRA_ASM=quarz4MHz.asm
MODEL=12f675
ARCH=pic14

include rules.inc

# --------------------------------------------------------------------------
